development:
  adapter: postgresql
  encoding: unicode
  database: flight_booking_development
  pool: 5
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: flight_booking_test
  pool: 5
  username: postgres
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: flight_booking_production
  pool: 5
  username: postgres
  password: postgres
